In [5]:
import pandas as pd
import os
import sys
import importlib

sys.path.append(os.path.abspath(".."))

import src.fantasy
import src.models
import src.features
import src.circuits

importlib.reload(src.fantasy)
importlib.reload(src.models)
importlib.reload(src.features)
importlib.reload(src.circuits)

from src.fantasy import build_fantasy_team, evaluate_fantasy_picks, generate_explanations
from src.data_loader import save_dataset, load_dataset
from src.features import build_features
from src.models import prepare_data, train_model, predict, build_fantasy_table, evaluate_model, tune_gainer_weights
from src.circuits import get_circuit_profiles, attach_circuit_profiles

In [6]:
df_2023 = load_dataset("../data/processed/race_results_2023.csv")
df_2024 = load_dataset("../data/processed/race_results_2024.csv")

df_2023 = build_features(df_2023)
df_2024 = build_features(df_2024)

X_train, y_train, X_test, y_test = prepare_data(df_2023, df_2024)
model = train_model(X_train, y_train)
predictions = predict(model, X_test)
fantasy_table = build_fantasy_table(df_2024, predictions)

In [7]:
circuit_profiles = get_circuit_profiles(df_2024)
circuit_profiles

,RaceName,circuit_type,drs_zones,avg_position_change,dnf_rate
0,Bahrain Grand Prix,permanent,3,NaN,NaN
1,Saudi Arabian Grand Prix,street,3,-0.33,0.0
2,Australian Grand Prix,semi-permanent,2,1.17,0.0
3,Japanese Grand Prix,permanent,1,0.00,0.0
4,Chinese Grand Prix,permanent,2,0.36,0.0
5,Miami Grand Prix,semi-permanent,3,-1.00,0.0
6,Emilia Romagna Grand Prix,permanent,1,0.89,0.0
7,Monaco Grand Prix,street,1,0.00,0.0
8,Canadian Grand Prix,semi-permanent,2,1.67,0.0
9,Spanish Grand Prix,permanent,2,0.27,0.0
10,Austrian Grand Prix,permanent,3,0.92,0.0
11,British Grand Prix,permanent,2,1.55,0.0
12,Hungarian Grand Prix,permanent,1,1.18,0.0
13,Belgian Grand Prix,permanent,1,0.78,0.0
14,Dutch Grand Prix,permanent,2,1.12,0.0
15,Italian Grand Prix,permanent,2,0.17,0.0
16,Azerbaijan Grand Prix,street,2,3.17,0.0
17,Singapore Grand Prix,street,3,0.86,0.0
18,United States Grand Prix,permanent,2,1.36,0.0
19,Mexico City Grand Prix,permanent,2,1.12,0.0
20,São Paulo Grand Prix,permanent,2,1.64,0.0
21,Las Vegas Grand Prix,street,2,1.50,0.0
22,Qatar Grand Prix,permanent,1,0.57,0.0
23,Abu Dhabi Grand Prix,permanent,2,1.60,0.0

In [8]:
fantasy_table = attach_circuit_profiles(fantasy_table, df_2024)
fantasy_table

,Abbreviation,TeamName,GridPosition,Position,Status,RaceName,RoundNumber,Year,PreviousPosition,Rolling3Average,...,Top10Finish,Top5Finish,DNF,Predicted,PredictedRounded,Confidence,circuit_type,drs_zones,avg_position_change,dnf_rate
0,ALB,Williams,14.0,18.0,Finished,Miami Grand Prix,6,2024,12.0,13.666667,...,0,0,0,14.58,15,0.58,semi-permanent,3,-1.00,0.0
1,ALB,Williams,9.0,9.0,Finished,British Grand Prix,12,2024,18.0,13.000000,...,1,0,0,8.87,9,0.13,permanent,2,1.55,0.0
2,ALB,Williams,10.0,12.0,Finished,Belgian Grand Prix,14,2024,9.0,13.000000,...,0,0,0,13.24,13,3.24,permanent,1,0.78,0.0
3,ALB,Williams,9.0,9.0,Finished,Italian Grand Prix,16,2024,12.0,10.000000,...,1,0,0,7.90,8,1.10,permanent,2,0.17,0.0
4,ALB,Williams,9.0,7.0,Finished,Azerbaijan Grand Prix,17,2024,9.0,9.333333,...,1,0,0,9.03,9,0.03,street,2,3.17,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,VER,Red Bull Racing,4.0,6.0,Finished,Abu Dhabi Grand Prix,24,2024,1.0,4.000000,...,1,0,0,6.92,7,2.92,permanent,2,1.60,0.0
244,ZHO,Kick Sauber,17.0,14.0,Finished,Azerbaijan Grand Prix,17,2024,14.0,14.000000,...,0,0,0,14.35,14,2.65,street,2,3.17,0.0
245,ZHO,Kick Sauber,19.0,15.0,Finished,São Paulo Grand Prix,21,2024,14.0,14.333333,...,0,0,0,14.87,15,4.13,permanent,2,1.64,0.0
246,ZHO,Kick Sauber,13.0,13.0,Finished,Las Vegas Grand Prix,22,2024,15.0,14.000000,...,0,0,0,13.68,14,0.68,street,2,1.50,0.0
247,ZHO,Kick Sauber,12.0,8.0,Finished,Qatar Grand Prix,23,2024,13.0,12.000000,...,1,0,0,10.13,10,1.87,permanent,1,0.57,0.0